### ISSUE TITLE
Current Time in Docker Log

### ISSUE THREAD

**Issue by ECKoBASE** [cmer/forever-internets#4]
Hi I have started using this Docker recently and it works amazingly!
It's currently running off my Synology NAS which is amazing, after hours of trying to find a device that would fix my issue but hey again thanks for writing this.

I just have suggestion/request are we able to change the Time Zone for the Logging?
(This would be good to present to my ISP when i have outages)

**Comment by cmer** [comment]
What time zone does it give you? It should just show you the container timezone, no? Is it because the container defaults to UTC?

**Comment by ECKoBASE** [comment]
Well this is what i get in the docker log, not sure what time zone this is. Definitely not mine haha

![Screenshot (157)](https://user-images.githubusercontent.com/17170386/101321574-7d752f80-38b5-11eb-956e-3fbb67251dd5.png)

**Comment by cmer** [comment]
Yeah that's UTC. Pretty standard. 

If you want your own time zone, try setting the [TZ environment variable](https://confluence.atlassian.com/kb/how-to-set-the-timezone-for-docker-container-976780914.html). Not sure if it'll work with this particular image though.
