### ISSUE TITLE
Docker Crash After Latest Update

### ISSUE THREAD

**Issue by ECKoBASE** [cmer/forever-internets#5]
Updated My Docker Container after seeing the NEW Update *LATEST* (Made 20 Days Ago).
Since the Upgrade Getting Crash Errors (See Attached Image)
*Even Deleted & Started Fresh and Still Having Issues.
#HALP!
![forever-internets issue](https://user-images.githubusercontent.com/17170386/104976147-70b73000-5a4c-11eb-951c-47b524272fd8.JPG)

**Comment by ECKoBASE** [comment]
Any suggestions??

**Comment by ECKoBASE** [comment]
Hello!?

**Comment by cmer** [comment]
Can you show a full width log? The important part of the error message is cut.

**Comment by ECKoBASE** [comment]
> Can you show a full width log? The important part of the error message is cut.

![Screenshot (169)](https://user-images.githubusercontent.com/17170386/117378225-1d41f280-af14-11eb-8828-1cf6996dac26.png)

Done!

**Comment by cmer** [comment]
Try updating your image to the latest version. It should fix your issue.

**Comment by ECKoBASE** [comment]
> Try updating your image to the latest version. It should fix your issue.

Thanks Now Working!
